language: php

php:
  - 7.0
  - 7.1

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
    - psql -c 'create database travis_ci_test;' -U postgres

script: phpunit --coverage-text`

services:
  - mysql
  - postgresql
