#imports:
#    - { resource: parameters.yml }
#    - { resource: security.yml }

parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: null
    database_name: andreybolonin
    database_user: postgres
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: null
    mailer_encryption: null
    mailer_user: null
    mailer_password: null
    websocket_host: 127.0.0.1
    websocket_port: 8080
    session_handler: session.handler.native_file
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true

        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/rest/(latest|v1)/pinbars, role: ROLE_USER }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    default_locale:           "%locale%"
    trusted_proxies:          ~
    session:
        name:                 CRMID
        handler_id:           %session_handler%
        save_path:            %kernel.root_dir%/cache/sessions
        gc_maxlifetime:       3600
        cookie_httponly:      true
    fragments:
        enabled:              true
        path:                 /_fragment # used for controller action in template
    serializer:
        enabled:              true

# Twig Configuration
twig:
    debug:                    "%kernel.debug%"
    strict_variables:         "%kernel.debug%"
    exception_controller:     "FOS\RestBundle\Controller\ExceptionController::showAction"
    globals:
        bap:
            layout:           ::base.html.twig  # default layout across all Oro bundles
        ws:
            port:             "%websocket_port%"
            host:             "%websocket_host%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:                "%mailer_transport%"
    host:                     "%mailer_host%"
    port:                     "%mailer_port%"
    encryption:               "%mailer_encryption%"
    username:                 "%mailer_user%"
    password:                 "%mailer_password%"
    spool:                    { type: memory }

#fos_rest:
#    view:
#        failed_validation: HTTP_BAD_REQUEST
#        default_engine: php
#        formats:
#            json: true
#            xml: true
#    format_listener:
#        prefer_extension: true
#    body_listener:
#        decoders:
#            json: fos_rest.decoder.json
#            xml: fos_rest.decoder.xml
#    routing_loader:
#        default_format: json

#fos_js_routing:
#    routes_to_expose:         [oro_*]

#be_simple_soap:
#    cache:
#        type:                 disk
#        lifetime:             86400
#        limit:                5
#    services:
#        soap:
#            namespace:        urn:OroPlatform
#            binding:          rpc-literal
#            resource:         .
#            resource_type:    oro_soap

#stof_doctrine_extensions:
#    default_locale: en
#    translation_fallback: true
#    orm:
#        default:
#            translatable:     true
#            tree:             true

services:
    twig.extension.intl:
         class: Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }
    doctrine.dbal.default.wrapped_connection:
        factory_service:      doctrine.dbal.default_connection
        factory_method:       getWrappedConnection
        class:                PDO
#    doctrine.metadata.cache:
#        parent: oro.cache.abstract
#        calls:
#            - [ setNamespace, [ "doctrine.metadata.cache" ] ]
    session.handler.pdo:
        class:                Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - "@doctrine.dbal.default.wrapped_connection"
            -
              db_table:       oro_session
              db_id_col:      id

#escape_wsse_authentication:
#    authentication_provider_class: Oro\Bundle\UserBundle\Security\WsseAuthProvider
#    authentication_listener_class: Oro\Bundle\UserBundle\Security\WsseAuthListener
#
#genemu_form:
#    select2: ~
#    autocomplete: ~
#
#clank:
#    web_socket_server:
#        port:                 %websocket_port%                # The port the socket server will listen on
#        host:                 %websocket_host%                # (optional) The host ip to bind to
#    session_handler:          session.handler.pdo
#    periodic:
#        -
#            service:          "oro_wamp.db_ping"
#            time:             60000                           # the time in milliseconds between the "tick" function being called
#
#a2lix_translation_form:
#    locales:                  [en, fr]
#    templating:               "OroUIBundle:Form:translatable.html.twig"
#
#lexik_maintenance:
#    authorized:
#        path:                 "maintenance|.*\.js"             # "maintenance" is only for demo purposes, remove in production!
##        ips:                  ["127.0.0.1"]                   # Optional. Authorized ip addresses
#    driver:
#        class:                Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver
#        options:
#            file_path:        %kernel.root_dir%/cache/maintenance_lock
#
##
## ORO Bundles config
##
#oro_distribution:
#    entry_point: ~
#
#oro_ui:
#    settings:
#        organization_name:
#            value:            "OroCRM"
#
#oro_require_js:
#    config:
#        waitSeconds: 0
#    build_path: "js/oro.min.js"
#    building_timeout: 3600
#    build:
#        optimize: "uglify2"
#        preserveLicenseComments: true
#
#oro_help:
#    defaults:
#        server: http://help.orocrm.com/
#        prefix: Third_Party
#    vendors:
#        Oro:
#            prefix: ~
#            alias: Platform
#        OroCRM:
#            prefix: ~
#            alias: CRM
#    routes:
#        oro_default:
#            uri: Platform/OroDashboardBundle
#
#oro_theme:
#    active_theme: oro

# imported from config_prod.yml

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     EasymedBundle\Entity\User


    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
