services:
#    easymed.example:
#        class: EasymedBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    easymed.admin.med_card:
        class: EasymedBundle\Admin\MedCardAdmin
        arguments: [~, EasymedBundle\Entity\MedCard, EasymedBundle:MedCardAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: MedCard}
