services:
#    easymed.example:
#        class: EasymedBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    easymed.locale_listener:
          class: EasymedBundle\EventListener\LocaleListener
          arguments: ["%kernel.default_locale%", %locales%, "@router"]
          tags:
              - { name: kernel.event_subscriber }

#    SkyFlow_app.admin.airport:
#        class: SkyFlow\AppBundle\Admin\AirportAdmin
#        arguments: [~, SkyFlow\AppBundle\Entity\Airport, SonataAdminBundle:CRUD]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: Airport}
